# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for root project Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for intellij-aicoder module
  - package-ecosystem: "gradle"
    directory: "/intellij-aicoder"
    target-branch: "next"
    schedule:
      interval: "daily"
    groups:
      intellij-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "next"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"