name: Build
on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.logging.level=info"
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
      pluginVerifierHomeDir: ${{ steps.properties.outputs.pluginVerifierHomeDir }}
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git --version
          echo "Git configuration:"
          git config --list
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
        with:
          working-directory: intellij-aicoder
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Print Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Print Gradle version
        working-directory: intellij-aicoder
        run: ../gradlew --version

      - name: Export Properties
        working-directory: intellij-aicoder
        id: properties
        shell: bash
        run: |
          echo "Starting properties export..."
          PROPERTIES="$(../gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          CHANGELOG="$(../gradlew getChangelog --unreleased --no-header --console=plain -q)"
          echo "Detected version: $VERSION"
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "pluginVerifierHomeDir=~/.pluginVerifier" >> $GITHUB_OUTPUT
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Properties export completed"

      - name: Build plugin
        working-directory: intellij-aicoder
        run: |
          echo "Starting plugin build..."
          ./gradlew buildPlugin --info
          echo "Plugin build completed"

      - name: Prepare Plugin Artifact
        working-directory: intellij-aicoder
        id: artifact
        shell: bash
        run: |
          echo "Preparing plugin artifact..."
          cd ${{ github.workspace }}/intellij-aicoder/build/distributions
          FILENAME=`ls *.zip`
          echo "Found artifact: $FILENAME"
          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT
          echo "Artifact preparation completed"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          working-directory: intellij-aicoder
          name: ${{ steps.artifact.outputs.filename }}
          path: intellij-aicoder/build/distributions/*
      - name: List uploaded artifacts
        run: |
          echo "Uploaded artifacts in distributions directory:"
          ls -la intellij-aicoder/build/distributions/

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.logging.level=info"
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git --version
          echo "Git configuration:"
          git config --list
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
        with:
          working-directory: intellij-aicoder
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Print Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Print Gradle version
        working-directory: intellij-aicoder
        run: ../gradlew --version

      - name: Run Tests
        working-directory: intellij-aicoder
        run: |
          echo "Starting test execution..."
          ../gradlew check --info
          echo "Test execution completed"

      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: tests-result
          path: intellij-aicoder/build/reports/tests
      - name: Print test summary
        if: always()
        run: |
          echo "Test results summary:"
          [ -f intellij-aicoder/build/reports/tests/test/index.html ] && cat intellij-aicoder/build/reports/tests/test/index.html | grep -A 5 "<div class=\"summary\">"

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v4
        with:
          files: intellij-aicoder/build/reports/kover/report.xml

  verify:
    name: Verify plugin
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git --version
          echo "Git configuration:"
          git config --list
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
        with:
          working-directory: intellij-aicoder
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Print Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Print Gradle version
        working-directory: intellij-aicoder
        run: ../gradlew --version

      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v4
        with:
          path: ${{ needs.build.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('intellij-aicoder/build/listProductsReleases.txt') }}

      - name: Run Plugin Verification tasks
        working-directory: intellij-aicoder
        run: ../gradlew verifyPlugin -Dplugin.verifier.home.dir=${{ needs.build.outputs.pluginVerifierHomeDir }}

      - name: Collect Plugin Verifier Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pluginVerifier-result
          path: intellij-aicoder/build/reports/pluginVerifier

  releaseDraft:
    name: Release draft
    if: github.event_name != 'pull_request'
    needs: [ build, test, verify ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git --version
          echo "Git configuration:"
          git config --list
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
        with:
          working-directory: intellij-aicoder
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Print Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Print Gradle version
        working-directory: intellij-aicoder
        run: ../gradlew --version

      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      - name: Create Release Draft
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ needs.build.outputs.version }}" \
            --draft \
            --title "v${{ needs.build.outputs.version }}" \
            --notes "${{ needs.build.outputs.changelog }}"
          RELEASE_URL=$(gh release view "v${{ needs.build.outputs.version }}" --json url -q .url)
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./artifact

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.release_url }}
          asset_path: ./artifact/intellij-aicoder-${{ needs.build.outputs.version }}/intellij-aicoder-${{ needs.build.outputs.version }}.zip
          asset_name: intellij-aicoder-${{ needs.build.outputs.version }}.zip
          asset_content_type: application/zip